pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m blah.py'
                stash(name: 'compiled-results', includes: 'sources/*.py')
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'blah'
                }
            }
            steps {
                sh 'py.test blah.py'
            }
            post {
                always {
                    do this
                }
            }
        }
        stage('Deliver') {
            agent any
            environment {
                VOLUME = '{pwd}/sources'
            }
            steps {
                dir(this) {
                    unstash(name: 'compiled-results')
                    sh "docker run --rm myapp:latest 'pyinstaller -F'"
                }
            }
            post {
                success {
                    do this
                    remove image
                }
            }
        }
    }
}